easy_admin:
    entities:
      User:
          class: App\Entity\User
          list:
            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            item_permission: 'ROLE_ADMIN'
          form:
              fields:
                  - {property: 'email'}
                  - {property: 'password'}
      Category:
          class: App\Entity\Category
          list:
            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            item_permission: 'ROLE_ADMIN'
          form:
              fields:
                  - {property: 'name'}
      Program:
          class: App\Entity\Program
          list:
            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            item_permission: 'ROLE_ADMIN'
            fields: ['title', 'category', 'synopsis', 'country', 'poster', {property: 'poster', type: 'image', base_path: '%upload_directory%'}] #This line is to display the image but fix needed
          form:
              fields:
                  - {property: 'title', label: 'Title'}
                  - {property: 'category', label: 'Category'}
                  - {property: 'synopsis', label: 'Synopsis'}
                  - {property: 'country', label: 'Country'}
                  - {property: 'posterFile', type: 'vich_image', base_path: '%upload_directory%', label: 'Poster'}
                  - {property: 'updatedAt', label: 'Updated at'}
      Season:
          class: App\Entity\Season
          list:
            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            item_permission: 'ROLE_ADMIN'
          form:
              fields:
                  - {property: 'number',, label: 'Number'}
                  - {property: 'year', label: 'Year'}
                  - {property: 'description',, label: 'Description'}
                  - {property: 'program', label: 'Program'}
                  - {property: 'video', label: 'Video (must be a url)'}

      Episode:
          class: App\Entity\Episode
          list:
              actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
              item_permission: 'ROLE_ADMIN'
              fields: ['title', 'number', 'image', 'season', {property: 'image', type: 'image', base_path: '%upload_directory%'}] #This line is to display the image but fix needed
          form:
              fields:
                  - {property: 'title', label: 'Title'}
                  - {property: 'number', label: 'Number'}
                  - {property: 'summary', label: 'Summary'}
                  - {property: 'season', label: 'Season'}
                  - {property: 'imageFile', type: 'vich_image', base_path: '%upload_directory%', label: 'Image'}
                  - {property: 'updatedAt', label: 'Updated at'}

      Actor:
          class: App\Entity\Actor
          list:
              fields: ['name','programs','nationality','description','updatedAt', {property: 'picture', type: 'image', base_path: '%upload_directory%'}] #This line is to display the image but fix needed
              actions:
                  - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                  - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
              item_permission: 'ROLE_ADMIN'
            
          form:
              fields:
                  - {property: 'name', label: 'Name'}
                  - {property: 'programs', label: 'Programs'}
                  - {property: 'nationality', label: 'Nationality'}
                  - {property: 'description', label: 'Description'}
                  - {property: 'pictureFile', type: 'vich_image', base_path: '%upload_directory%', label: 'Picture'}
                  - {property: 'updatedAt', label: 'Updated at'}

