vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /images/posters  # Affiches de film
            # Chemin vers le dossier de stockage
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true

        picture_file:
            uri_prefix: /images/pictures  # Photos d'acteurs
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true

        picture_director_file:
            uri_prefix: /images/director_pictures  # Photos de réalisateurs
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true

        image_file:
            uri_prefix: /images/images  # Images de film
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
